nordic_repo: "https://github.com/EliverLara/Nordic.git"

gnome_packages_fedora:
  - gnome-extensions-app
  - gnome-shell-extension-user-theme
  - papirus-icon-theme

# GNOME Shell extensions (UUIDs) — these are not distro packages
gnome_shell_extensions:
  - tactile@github.com
  - gsconnect@andyholmes.github.io
  - clipboard-indicator@tudmotu.com
  - appindicatorsupport@rgcjonas.gmail.com
  - boostvolume@shaquib.dev
