- name: Install requirements packages for docker
  ansible.builtin.command:
    cmd: "{{ ansible_facts['python']['executable'] }} -m pip install --break-system-packages {{ item }}"
  with_items:
    - "requests==2.31.0"
    - docker
  tags:
    - containers

- name: Set up a PostGIS container
  community.docker.docker_container:
    name: postgres
    image: postgis/postgis:16-3.5-alpine
    state: started
    restart_policy: always
    ports:
      - "5432:5432"
    env:
      POSTGRES_PASSWORD: pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  tags:
    - containers

- name: Set up a Redis container
  community.docker.docker_container:
    name: redis
    image: redis:alpine
    state: started
    restart_policy: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  tags:
    - containers
