return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  branch = 'main',
  -- main = 'nvim-treesitter.configs',
  lazy = false,

  opts = {
    ensure_installed = {
      'python',
      'lua',
      'go',
      'html',
      'gitignore',
      'gitcommit',
      'diff',
      'csv',
      'bash',
      'dockerfile',
      'javascript',
      'json',
      'make',
      'sql',
      'requirements',
      'vim',
      'yaml',
      'ssh_config',
      'caddy',
      'c',
      'luadoc',
      'markdown',
      'markdown_inline',
      'query',
      'vimdoc',
    },
    auto_install = true,
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = {},
    },
    indent = { enable = true },
  },
}
