- name: Ensure the directory for apt keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download and dearmor the WezTerm GPG key
  ansible.builtin.command:
    cmd: "curl -fsSL https://apt.fury.io/wez/gpg.key | gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg"
  args:
    creates: /etc/apt/keyrings/wezterm-fury.gpg

- name: Add the WezTerm repository to apt sources
  ansible.builtin.copy:
    content: |
      deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *
    dest: /etc/apt/sources.list.d/wezterm.list
    mode: '0644'

- name: Install packages on Pop!_OS
  ansible.builtin.package:
    name: "{{ pop_os_packages }}"
    state: present
