- name: Include vars on Fedora
  ansible.builtin.include_vars: fedora.yaml
  when: ansible_facts['os_family'] == "RedHat"

- name: Include vars on Pop!_OS
  ansible.builtin.include_vars: pop_os.yaml
  when: ansible_facts['os_family'] == "Debian"

- name: Include vars on macOS
  ansible.builtin.include_vars: macos.yaml
  when: ansible_facts['os_family'] == "Darwin"

- name: Install packages on Fedora
  ansible.builtin.include_tasks: install_fedora.yaml
  when: ansible_facts['os_family'] == "RedHat"

- name: Install packages on Pop!_OS
  ansible.builtin.include_tasks: install_pop_os.yaml
  when: ansible_facts['os_family'] == "Debian"

- name: Install packages on macOS
  ansible.builtin.include_tasks: install_macos.yaml
  when: ansible_facts['os_family'] == "Darwin"

