- name: Install required packages
  include_tasks: install_packages.yaml

- name: Link dotfiles
  ansible.builtin.shell: |
    if [ -e "{{ item.dest }}" ] && [ ! -L "{{ item.dest }}" ]; then
      mv "{{ item.dest }}" "{{ item.dest }}.backup"
    fi
    ln -sfn "{{ item.src }}" "{{ item.dest }}"
  args:
    executable: /bin/bash
  loop: "{{ dotfiles }}"
  tags:
    - link_files

