- name: Install required packages
  include_tasks: install_packages.yaml

- name: Link dotfiles
  ansible.builtin.shell: |
    dest="$(eval echo {{ item.dest }})"
    src="$(eval echo {{ item.src }})"
    if [ -e "$dest" ] && [ ! -L "$dest" ]; then
      mv "$dest" "$dest.backup"
    fi
    mkdir -p "$(dirname "$dest")"
    ln -sfn "$src" "$dest"
  args:
    executable: /bin/bash
  loop: "{{ dotfiles }}"
  tags:
    - link_files

