- name: Add Podman repo on Fedora
  ansible.builtin.include_tasks: repo_fedora.yaml

- name: Install Podman (container runtime)
  block:
    - name: Install Podman and shims
      become: true
      ansible.builtin.package:
        name: "{{ container_runtime_packages }}"
        state: present

    - name: Enable podman socket
      become: true
      ansible.builtin.systemd:
        name: podman.socket
        enabled: yes
        state: started
