- name: Install Podman (container runtime)
  block:
    - name: Install Podman and shims on Fedora/Pop!_OS
      become: true
      ansible.builtin.package:
        name: "{{ container_runtime_packages }}"
        state: present
      when: ansible_facts['os_family'] in ['RedHat','Debian']

    - name: Enable podman socket
      become: true
      ansible.builtin.systemd:
        name: podman.socket
        enabled: yes
        state: started
      when: ansible_facts['os_family'] in ['RedHat','Debian']
