- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install prerequisites for Docker
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create the directory for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to Apt sources
  ansible.builtin.copy:
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list

- name: Update apt package index again
  ansible.builtin.apt:
    update_cache: yes

